INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=6mBJtUw79sM&list=PLlgNoU93QSLGsP9vJHoiKv_o6WWLOyNnY&index=27', '1g8bj4b');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=6mBJtUw79sM&list=PLlgNoU93QSLGsP9vJHoiKv_o6WWLOyNnY&index=26', '1g8bj48');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=6mBJtUw79sM&list=PLlgNoU93QSLGsP9vJHoiKv_o6WWLOyNnY&index=25', '1g8bj46');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=6mBJtUw79sM&list=PLlgNoU93QSLGsP9vJHoiKv_o6WWLOyNnY&index=24', '1g8bj44');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=6mBJtUw79sM&list=PLlgNoU93QSLGsP9vJHoiKv_o6WWLOyNnY&index=2', '1g8bj42');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=6mBJtUw79sM&list=PLlgNoU93QSLGsP9vJHoiKv_o6WWLOyNnY&index=23', '1g8bj3v');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES('https://www.youtube.com/watch?v=6mBJtUw79sM&list=PLlgNoU93QSLGsP9vJHoiKv_o6WWLOyNnY&index=22', '1g8bj3s');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=6mBJtUw79sM&list=PLlgNoU93QSLGsP9vJHoiKv_o6WWLOyNnY&index=21', '1g8bj3q');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=6mBJtUw79sM&list=PLlgNoU93QSLGsP9vJHoiKv_o6WWLOyNnY&index=20', '1g8bj3i');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=6mBJtUw79sM&list=PLlgNoU93QSLGsP9vJHoiKv_o6WWLOyNnY&index=19', '1g8bj39');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=6mBJtUw79sM&list=PLlgNoU93QSLGsP9vJHoiKv_o6WWLOyNnY&index=18', '1g8bj37');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=6mBJtUw79sM&list=PLlgNoU93QSLGsP9vJHoiKv_o6WWLOyNnY&index=17', '1g8bj34');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=6mBJtUw79sM&list=PLlgNoU93QSLGsP9vJHoiKv_o6WWLOyNnY&index=16', '1g8bj31');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=6mBJtUw79sM&list=PLlgNoU93QSLGsP9vJHoiKv_o6WWLOyNnY&index=15', '1g8bj2v');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=-hLk8GXOaJg&list=PLlgNoU93QSLGsP9vJHoiKv_o6WWLOyNnY&index=13', '1g8bj2l');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES('https://www.youtube.com/watch?v=pg9k-lAM7M8&list=PLlgNoU93QSLGsP9vJHoiKv_o6WWLOyNnY&index=1', '1g8bj0k');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=AQqnOROEM5c&list=PLlgNoU93QSLGsP9vJHoiKv_o6WWLOyNnY&index=2', '1g8b8b7');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=HcuhbdPiifA&list=PLlgNoU93QSLGsP9vJHoiKv_o6WWLOyNnY&index=3', '1g8b67f');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=p2OOblCTXnY&list=PLUJJN9tmVTj1czFMt9IKi6wge9GnmMTN3&index=17', '1g8b64u');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=pFvcqNhROgA&list=PLUJJN9tmVTj1czFMt9IKi6wge9GnmMTN3&index=15', '1g8b64n');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=F93iENzUcWc&list=PLUJJN9tmVTj1czFMt9IKi6wge9GnmMTN3&index=14', '1g8b64f');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=xccEiY3V6s4&list=PLUJJN9tmVTj1czFMt9IKi6wge9GnmMTN3&index=13', '1g8b643');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=ERvdz0w_Zgk&list=PLUJJN9tmVTj1czFMt9IKi6wge9GnmMTN3&index=11', '1g8b63l');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES('https://www.youtube.com/watch?v=88D95QYtduM&list=PLUJJN9tmVTj1czFMt9IKi6wge9GnmMTN3&index=8', '1g8b62f');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=LU04P6t2wKU&list=PLUJJN9tmVTj1czFMt9IKi6wge9GnmMTN3&index=6', '1g8b629');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=Wjx2xnFTj8I&list=PLUJJN9tmVTj1czFMt9IKi6wge9GnmMTN3&index=5', '1g8b5td');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=0Nu1a9Te6ac&list=PLUJJN9tmVTj1czFMt9IKi6wge9GnmMTN3&index=4', '1g8b59u');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=IpSr9CDVGz0&list=PLUJJN9tmVTj1czFMt9IKi6wge9GnmMTN3&index=3', '1g8b59e');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=m96PLSEIALg&list=PLUJJN9tmVTj1czFMt9IKi6wge9GnmMTN3&index=2', '1g8b599');
INSERT INTO `link` (`origin_link`, `shorten_link`) VALUES( 'https://www.youtube.com/watch?v=WIU8-2hqyqM&list=PLUJJN9tmVTj1czFMt9IKi6wge9GnmMTN3&index=1', '1g8b58u');